import streamlit as st
from time import sleep
from random import choice

st.set_page_config(
    page_title='Career Survey',
    layout='wide',
    page_icon='🎓',
)

CAREER_OPTIONS = {
    'Aerospace': [1, 2, 3, 112, 134, 125, 106, 110, 145, 107],
    'Engineer': [1, 3, 102, 113, 133, 127, 148, 131, 109],
    'Architect': [1, 4, 102, 127, 132, 110, 111, 116],
    'Military': [2, 3, 105, 134, 112, 106, 139, 145],
    'Healthcare': [1, 2, 3, 5, 109, 118, 119, 148, 126, 142],
    'Computer Science': [4, 102, 117, 106, 103, 101],
    'Environmental Science': [1, 3, 112, 125, 111, 147, 141, 118],
    'Culinary': [2, 4, 5, 107, 130, 110, 123, 109, 141, 136],
    'Agriculture': [2, 3, 112, 141, 146, 148, 130, 110, 142],
    'Teaching': [1, 4, 5, 144, 123, 113, 148, 136, 141, 107],
    'Construction': [2, 3, 4, 107, 132, 130, 110, 103, 141, 139],
    'Finance': [1, 4, 102, 140, 145, 111, 119, 123],
    'Marketing': [1, 4, 114, 123, 124, 111, 109, 114],
    'Software Developer': [4, 102, 117, 106, 103, 101],
    'Graphic Designer': [4, 101, 116, 107],
    'Data Scientist': [1, 102, 106, 103, 109],
    'Civil Engineer': [1, 2, 102, 107, 127, 132, 141, 139],
    'Marketing Manager': [1, 4, 114, 123, 124, 111, 109, 114],
    'Teacher': [1, 4, 5, 144, 123, 113, 148, 136, 141, 107],
    'Nurse': [1, 2, 3, 5, 109, 118, 119, 148, 126, 142],
    'Chef': [2, 4, 5, 107, 130, 110, 123, 109, 141, 136],
    'Mechanical Engineer': [1, 2, 102, 107, 127, 141, 139],
    'Electrician': [2, 3, 4, 107, 130, 110, 141, 139],
    'Photographer': [4, 101, 110, 114],
    'Architect': [1, 4, 102, 127, 132, 110, 111, 116],
    'Financial Analyst': [1, 4, 102, 140, 145, 111, 119, 123],
    'Lawyer': [1, 4, 113, 140, 145, 109, 126],
    'Dentist': [1, 109, 118, 119, 126, 142],
    'Police Officer': [1, 2, 3, 105, 106, 139, 145],
    'Firefighter': [2, 3, 105, 106, 139, 145],
    'Pilot': [1, 3, 102, 134, 141],
    'Biologist': [1, 3, 102, 103, 112, 118, 125],
    'Event Planner': [4, 101, 114, 123, 109],
    'Social Worker': [1, 4, 101, 123, 109, 148],
    'Pharmacist': [1, 109, 118, 119, 126],
    'Interior Designer': [4, 101, 110, 107, 123, 128],
    'Electrician': [2, 3, 4, 107, 130, 110, 141, 139],
    'Psychologist': [1, 4, 101, 118, 119, 126, 148],
    'Actor': [4, 106, 107, 114, 137],
    'Fitness Trainer': [2, 4, 5, 109, 118, 119, 126],
    'Real Estate Agent': [4, 107, 123, 126],
    'Mechanic': [2, 4, 107, 130, 110, 139],
    'Fashion Designer': [4, 101, 107, 110, 123, 108],
    'Biomedical Engineer': [1, 102, 107, 127, 141],
    'Geologist': [1, 3, 102, 103, 112, 118, 125],
    'Journalist': [4, 101, 106, 109, 114],
    'Human Resources Manager': [1, 4, 114, 123, 109],
    'Plumber': [2, 3, 4, 107, 130, 110, 141, 139],
    'Accountant': [1, 4, 102, 140, 145, 111, 119],
    'Dietitian': [1, 109, 118, 119, 126, 142],
    'Biotechnologist': [1, 102, 107, 112, 141],
    'Electrician': [2, 3, 4, 107, 130, 110, 141, 139],
    'Paramedic': [2, 3, 5, 109, 118, 119, 126],
    'Painter': [2, 3, 4, 107, 130, 110, 141],
    'Computer Programmer': [4, 102, 117, 106, 103, 101],
    'Veterinarian': [1, 109, 118, 119, 126, 142],
    'Mechanical Engineer': [1, 2, 102, 107, 127, 141, 139],
    'Chemical Engineer': [1, 2, 102, 107, 127, 141, 139],
    'Aerospace Engineer': [1, 2, 3, 112, 134, 125, 106, 110, 145, 107],
    'Physicist': [1, 102, 103, 125, 118],
    'Mathematician': [1, 102, 103, 125, 118],
    'Translator': [4, 101, 141, 123],
    'Speech Therapist': [1, 109, 118, 119, 126],
    'Bartender': [2, 4, 107, 123, 109],
    'Agricultural Engineer': [1, 2, 102, 107, 112, 141],
    'Forester': [2, 3, 112, 141, 147],
    'Marine Biologist': [1, 3, 112, 118, 125],
    'Zoologist': [1, 3, 112, 118, 125],
    'Social Media Manager': [1, 4, 114, 123, 124, 111, 109],
    'Web Designer': [4, 102, 106, 110, 101],
    'Fashion Stylist': [4, 101, 107, 110, 123, 108],
    'Event Coordinator': [4, 101, 114, 123, 109],
    'Investment Banker': [1, 4, 102, 140, 145, 111, 119],
    'Surveyor': [1, 2, 3, 107, 132, 141, 147],
    'Electrician': [2, 3, 4, 107, 130, 110, 141, 139],
    'Carpenter': [2, 3, 4, 107, 130, 110, 141, 139],
    'Librarian': [1, 4, 101, 123, 109],
    'Air Traffic Controller': [1, 102, 106, 134, 141],
    'Hotel Manager': [1, 4, 114, 123, 109],
    'Chiropractor': [1, 109, 118, 119, 126],
    'Security Guard': [2, 106, 139, 145],
    'Insurance Agent': [1, 4, 102, 140, 145, 111, 119],
    'Environmental Engineer': [1, 2, 3, 112, 125, 110, 141],
    'Economist': [1, 4, 102, 140, 145, 111, 119],
    'Dancer': [4, 106, 119, 107],
    'Actor': [4, 106, 107, 114, 137],
    'Biochemist': [1, 102, 107, 112, 141],
    'Orthodontist': [1, 109, 118, 119, 126],
    'Meteorologist': [1, 3, 112, 125, 118],
    'Flight Attendant': [4, 106, 109, 123, 134],
    'Archaeologist': [1, 3, 102, 113, 141],
    'Speech Writer': [4, 106, 109, 123, 114],
    'Flight Instructor': [1, 102, 106, 134, 141],
    'Probation Officer': [1, 4, 101, 123, 109],
    'Veterinary Technician': [2, 109, 118, 119, 126, 142],
    'Personal Trainer': [2, 4, 5, 109, 118, 119, 126],
    'Phlebotomist': [2, 109, 118, 119, 126],
    'Forensic Scientist': [1, 102, 103, 112, 141],
    'Landscape Architect': [4, 102, 107, 132, 110, 111, 116],
    'Physical Therapist': [1, 2, 109, 118, 119, 126],
    'Technical Writer': [4, 106, 110, 101],
    'Sound Engineer': [4, 104, 106, 110, 114],
    'Medical Illustrator': [1, 102, 103, 110, 114],
    'Museum Curator': [1, 4, 101, 123, 109],
    'Glass Blower': [4, 101, 106, 107],
    'Ranger': [2, 3, 112, 141, 147],
    'Public Relations Specialist': [4, 106, 114, 123, 109],
    'Child Psychologist': [1, 4, 101, 118, 119, 126],
    'Translator': [4, 101, 141, 123],
    'Geographer': [1, 3, 102, 103, 112, 141],
    'Clinical Psychologist': [1, 4, 101, 118, 119, 126],
    'Jewelry Designer': [4, 101, 110, 107, 123],
    'Social Media Influencer': [4, 101, 123, 109],
    'Ethical Hacker': [1, 102, 106, 101],
    'App Developer': [4, 102, 117, 106, 103, 101],
    'Audiologist': [1, 109, 118, 119, 126],
    'Optometrist': [1, 109, 118, 119, 126],
    'Speech Pathologist': [1, 109, 118, 119, 126],
    'Criminal Investigator': [1, 4, 113, 145, 109],
    'Forensic Accountant': [1, 4, 102, 140, 145, 111, 119],
    'Urban Planner': [1, 3, 102, 132, 110, 111, 138],
    'Fashion Buyer': [4, 101, 107, 110, 123, 108],
    'Choreographer': [4, 106, 107, 119],
    'Personal Chef': [2, 4, 5, 107, 130, 110, 123, 109],
    'Public Health Analyst': [1, 3, 5, 109, 118, 119, 126],
    'Sports Agent': [1, 4, 105, 106, 109, 123],
    'Fashion Blogger': [4, 101, 123, 109, 108],
    'Forensic Psychologist': [1, 4, 113, 145, 109],
    'Art Therapist': [1, 4, 101, 106, 123, 109],
    'Speech Coach': [4, 106, 109, 123],
    'Cryptographer': [1, 102, 106, 101],
    'Biomedical Scientist': [1, 102, 107, 112, 141],
    'Clinical Lab Technician': [2, 109, 118, 119, 126],
    'Music Therapist': [1, 4, 104, 106, 109, 123],
    'Technical Illustrator': [1, 102, 103, 106, 110, 101],
    'Mortician': [1, 4, 106, 109, 123],
    'Robotics Engineer': [1, 102, 107, 141],
    'Speech Scientist': [1, 109, 118, 119, 126],
    'Tattoo Artist': [4, 106, 107, 110, 101],
    'Social Worker': [1, 4, 101, 123, 109],
    'Personal Shopper': [4, 101, 107, 123],
    'Environmental Scientist': [1, 3, 112, 125, 111, 147, 141, 118],
    'FBI Agent': [1, 4, 105, 106, 139, 145],
    'Radiation Therapist': [1, 109, 118, 119, 126],
    'Dental Hygienist': [1, 109, 118, 119, 126],
    'Audiobook Narrator': [4, 106, 109, 123, 101],
    'Astronomer': [1, 102, 103, 125, 118],
    'Nuclear Physicist': [1, 102, 103, 125, 118],
    'Forensic Pathologist': [1, 4, 106, 109, 123, 113],
    'Ethnobotanist': [1, 3, 112, 141, 146, 148],
    'Cartographer': [1, 3, 102, 132, 110, 141],
    'Neuroscientist': [1, 102, 103, 118, 119, 126],
    'Genetic Counselor': [1, 102, 103, 118, 119, 126],
    'Robotics Technician': [2, 3, 102, 107, 141],
    'Crime Scene Investigator': [1, 4, 106, 109, 123, 113],
    'Ethical Hacker': [1, 102, 106, 101],
    'Cryptographer': [1, 102, 106, 101],
    'Astronaut': [1, 3, 102, 112, 125, 106, 110, 134],
    'Fine Artist': [4, 101, 106, 110, 114],
    'Florist': [4, 107, 110, 123, 109],
    'Wedding Planner': [4, 101, 107, 114, 123, 109],
    'Film Director': [4, 106, 109, 114, 123],
    'Automotive Engineer': [1, 2, 102, 107, 141],
    'Veterinary Surgeon': [1, 109, 118, 119, 126, 142],
    'Wildlife Biologist': [1, 3, 112, 118, 125],
    'Music Producer': [4, 104, 106, 109, 114],
    'Librarian': [1, 4, 101, 123, 109],
    'Audio Engineer': [4, 104, 106, 109, 110],
    'Biomedical Engineer': [1, 102, 107, 127, 141],
    'Food Scientist': [1, 109, 118, 119, 126, 130],
    'Forensic Toxicologist': [1, 109, 118, 119, 126, 113],
    'Fashion Illustrator': [4, 101, 107, 110, 114],
    'Bioinformatics Specialist': [1, 102, 107, 141],
    'Agricultural Scientist': [1, 3, 112, 141, 146, 148],
    'Astrophysicist': [1, 102, 103, 125, 118],
    'Furniture Designer': [4, 101, 107, 110, 128],
    'Jeweler': [4, 101, 110, 107],
    'Makeup Artist': [4, 101, 106, 107],
    'Forensic Anthropologist': [1, 4, 113, 145, 109],
    'Tutor': [1, 4, 144, 123, 113, 148, 136, 141, 107],
    'Corporate Trainer': [1, 4, 144, 123, 113, 148, 136, 141, 107],
    'Biomedical Technician': [2, 109, 118, 119, 126, 141],
    'Public Health Nurse': [1, 2, 3, 5, 109, 118, 119, 126, 142],
    'Forensic Psychologist': [1, 4, 113, 145, 109],
    'Fashion Merchandiser': [4, 101, 107, 110, 123, 108],
    'Cartoonist': [4, 101, 110, 107, 131],
    'Medical Examiner': [1, 4, 106, 109, 123, 113],
    'Urban Designer': [4, 101, 107, 110, 111, 132],
    'Botanist': [1, 3, 112, 141, 146, 148],
    'Ecologist': [1, 3, 112, 141, 146, 148],
    'Marine Engineer': [1, 2, 102, 107, 141],
    'Meteorologist': [1, 3, 112, 125, 118],
    'Industrial Designer': [4, 101, 107, 110, 111, 116],
    'Digital Marketing Specialist': [1, 4, 114, 123, 124, 111, 109],
    'Bioinformatics Scientist': [1, 102, 107, 141],
    'Orthopedic Surgeon': [1, 109, 118, 119, 126],
    'Environmental Health Specialist': [1, 3, 112, 141, 146, 148],
    'Physical Education Teacher': [1, 4, 5, 144, 123, 113, 148, 136, 141, 107],
    'Green Architect': [1, 4, 102, 127, 132, 110, 111, 116],
    'Conservationist': [1, 3, 112, 141, 146, 148],
    'Air Quality Analyst': [1, 3, 112, 141, 146, 148],
    'Oceanographer': [1, 3, 112, 141, 146, 148],
    'Neurosurgeon': [1, 109, 118, 119, 126],
    'Wildlife Photographer': [4, 101, 110, 114, 123],
    'Criminal Profiler': [1, 4, 113, 145, 109],
    'Ecological Economist': [1, 4, 102, 140, 145, 111, 119],
    'Behavioral Analyst': [1, 4, 101, 118, 119, 126],
    'Water Resource Engineer': [1, 2, 102, 107, 141],
    'Waste Management Specialist': [1, 3, 112, 141, 146, 148],
    'Urban Forester': [1, 3, 112, 141, 146, 148],
    'Toxicologist': [1, 102, 107, 112, 141],
    'Solar Energy Technician': [2, 3, 102, 107, 141],
    'Soil Conservationist': [1, 3, 112, 141, 146, 148],
    'River Guide': [2, 3, 107, 111, 147],
    'Renewable Energy Consultant': [1, 102, 107, 141],
    'Recycling Coordinator': [1, 3, 112, 141, 146, 148]
}

CAREER_DESCRIPTIONS = {
    'Aerospace': "Design, develop, and test aircraft, spacecraft, and missiles.",
    'Engineer': "Apply principles of science and mathematics to develop solutions for technical problems.",
    'Architect': "Design buildings, landscapes, and other structures.",
    'Military': "Defend the country and its interests through armed services.",
    'Healthcare': "Provide medical services to diagnose and treat illnesses and injuries.",
    'Computer Science': "Develop software and hardware solutions for computing problems.",
    'Environmental Science': "Study the environment and solve environmental problems.",
    'Culinary': "Prepare and cook food in various settings.",
    'Agriculture': "Grow crops and raise livestock for food production.",
    'Teaching': "Educate students in various subjects and grade levels.",
    'Construction': "Build and maintain structures and infrastructure.",
    'Finance': "Manage financial transactions and investments.",
    'Marketing': "Promote and sell products or services to consumers.",
    'Software Developer': "Design, build, and test software applications.",
    'Graphic Designer': "Create visual concepts using computer software or by hand.",
    'Data Scientist': "Analyze and interpret complex data to inform decision-making.",
    'Civil Engineer': "Plan, design, and oversee construction projects and infrastructure.",
    'Marketing Manager': "Plan and oversee marketing strategies to promote products or services.",
    'Teacher': "Instruct and educate students in various subjects and grade levels.",
    'Nurse': "Provide care for patients in healthcare settings.",
    'Chef': "Prepare and cook food in restaurants or other food service establishments.",
    'Mechanical Engineer': "Design, develop, and test mechanical devices.",
    'Electrician': "Install and maintain electrical systems in buildings and other structures.",
    'Photographer': "Capture and edit images for various purposes.",
    'Financial Analyst': "Analyze financial data to inform investment decisions.",
    'Lawyer': "Provide legal advice and representation to clients.",
    'Dentist': "Diagnose and treat dental problems and oral diseases.",
    'Police Officer': "Enforce laws and maintain public safety.",
    'Firefighter': "Respond to fires and other emergencies to protect life and property.",
    'Pilot': "Operate aircraft to transport passengers or cargo.",
    'Biologist': "Study living organisms and their interactions with the environment.",
    'Event Planner': "Plan and coordinate events such as weddings, conferences, and parties.",
    'Social Worker': "Provide support and assistance to individuals and families in need.",
    'Pharmacist': "Dispense medications and provide healthcare advice to patients.",
    'Interior Designer': "Plan and design interior spaces for homes, businesses, and other environments.",
    'Psychologist': "Study mental processes and behavior and provide therapy and counseling.",
    'Actor': "Portray characters in plays, movies, or television shows.",
    'Fitness Trainer': "Instruct and motivate individuals or groups in exercise activities.",
    'Real Estate Agent': "Buy, sell, and rent properties on behalf of clients.",
    'Mechanic': "Inspect, repair, and maintain vehicles and machinery.",
    'Fashion Designer': "Create clothing and accessories.",
    'Biomedical Engineer': "Apply engineering principles to healthcare and medical technology.",
    'Geologist': "Study the Earth's materials, structures, and processes.",
    'Journalist': "Investigate and report news stories for newspapers, magazines, and other media.",
    'Human Resources Manager': "Oversee the recruitment, training, and management of employees.",
    'Plumber': "Install and repair plumbing systems in homes and buildings.",
    'Accountant': "Prepare and examine financial records and ensure compliance with regulations.",
    'Dietitian': "Advise individuals and groups on nutrition and healthy eating habits.",
    'Biotechnologist': "Apply biological principles to develop products and technologies.",
    'Paramedic': "Provide emergency medical care to sick or injured patients.",
    'Painter': "Apply paint, stain, and other finishes to surfaces.",
    'Computer Programmer': "Write and test code for software applications and systems.",
    'Veterinarian': "Diagnose and treat illnesses and injuries in animals.",
    'Chemical Engineer': "Design and oversee processes for producing chemicals and related products.",
    'Physicist': "Study the fundamental principles of the universe.",
    'Mathematician': "Study patterns, relationships, and numerical data.",
    'Translator': "Convert written or spoken material from one language into another.",
    'Speech Therapist': "Assess and treat speech and language disorders.",
    'Bartender': "Mix and serve alcoholic beverages to customers.",
    'Agricultural Engineer': "Apply engineering principles to agriculture and farming.",
    'Forester': "Manage forests and woodlands for conservation and resource management.",
    'Marine Biologist': "Study marine organisms and their ecosystems.",
    'Zoologist': "Study animals and their behavior, characteristics, and habitats.",
    'Social Media Manager': "Manage and promote brands on social media platforms.",
    'Web Designer': "Design and create websites.",
    'Fashion Stylist': "Coordinate clothing and accessories for fashion shoots, shows, or events.",
    'Event Coordinator': "Plan and execute events such as conferences, weddings, and parties.",
    'Investment Banker': "Provide financial services and advice to corporations and governments.",
    'Surveyor': "Measure and map land and airspace boundaries.",
    'Carpenter': "Construct and repair wooden structures and fixtures.",
    'Librarian': "Manage and organize collections of books and other materials.",
    'Air Traffic Controller': "Coordinate the movement of air traffic to ensure safety and efficiency.",
    'Hotel Manager': "Oversee the operations of hotels and lodging establishments.",
    'Chiropractor': "Diagnose and treat musculoskeletal disorders, primarily through manual adjustments.",
    'Security Guard': "Monitor and protect property against theft, vandalism, and other illegal activity.",
    'Insurance Agent': "Sell insurance policies to individuals and businesses.",
    'Environmental Engineer': "Apply engineering principles to protect and preserve the environment.",
    'Economist': "Analyze and interpret economic data and trends.",
    'Dancer': "Perform choreographed dance routines for audiences.",
    'Actor': "Portray characters in plays, movies, or television shows.",
    'Biochemist': "Study the chemical processes and substances in living organisms.",
    'Orthodontist': "Diagnose and correct dental irregularities and malocclusions.",
    'Meteorologist': "Study the atmosphere and weather patterns.",
    'Flight Attendant': "Ensure the safety and comfort of airline passengers during flights.",
    'Archaeologist': "Study human history and prehistory through excavation of artifacts and sites.",
    'Speech Writer': "Write speeches for individuals or organizations.",
    'Flight Instructor': "Teach individuals how to fly aircraft.",
    'Probation Officer': "Supervise and support individuals who are on probation.",
    'Veterinary Technician': "Assist veterinarians in providing care for animals.",
    'Personal Trainer': "Instruct and motivate individuals or groups in exercise activities.",
    'Phlebotomist': "Collect blood samples from patients for medical testing.",
    'Forensic Scientist': "Analyze physical evidence to solve crimes.",
    'Landscape Architect': "Design outdoor spaces and landscapes.",
    'Physical Therapist': "Assist patients in recovering from injuries and illnesses through physical movement.",
    'Technical Writer': "Create instructional manuals and other technical documents.",
    'Sound Engineer': "Record and manipulate audio for various purposes.",
    'Medical Illustrator': "Create visual representations of medical and scientific subjects.",
    'Museum Curator': "Manage and oversee collections of artifacts and artwork in museums.",
    'Glass Blower': "Create glass objects and sculptures through the process of glassblowing.",
    'Ranger': "Protect and manage natural resources in parks and wilderness areas.",
    'Public Relations Specialist': "Manage communication between an organization and the public.",
    'Child Psychologist': "Diagnose and treat mental, emotional, and behavioral disorders in children.",
    'Translator': "Convert written or spoken material from one language into another.",
    'Geographer': "Study the Earth's landscapes, environments, and phenomena.",
    'Clinical Psychologist': "Diagnose and treat mental, emotional, and behavioral disorders.",
    'Jewelry Designer': "Design and create jewelry pieces.",
    'Social Media Influencer': "Create content and engage with followers on social media platforms.",
    'Ethical Hacker': "Test and secure computer systems and networks against cyber threats.",
    'App Developer': "Design and develop applications for mobile devices or computers.",
    'Audiologist': "Diagnose and treat hearing and balance disorders.",
    'Optometrist': "Examine and diagnose vision problems and eye diseases.",
    'Speech Pathologist': "Assess and treat speech and language disorders.",
    'Criminal Investigator': "Investigate crimes and gather evidence to solve cases.",
    'Forensic Accountant': "Investigate financial crimes and analyze financial records.",
    'Urban Planner': "Plan and design communities and urban environments.",
    'Fashion Buyer': "Select and purchase clothing and accessories for retail stores.",
    'Choreographer': "Create and direct dance routines and performances.",
    'Personal Chef': "Prepare meals for individuals or families in private homes.",
    'Public Health Analyst': "Analyze and interpret data to inform public health policies and programs.",
    'Sports Agent': "Represent and negotiate contracts for athletes.",
    'Fashion Blogger': "Create and share content about fashion trends and styles.",
    'Forensic Psychologist': "Apply psychology principles to criminal investigations and legal proceedings.",
    'Art Therapist': "Use art as a form of therapy to improve mental and emotional well-being.",
    'Speech Coach': "Provide instruction and guidance to improve public speaking skills.",
    'Cryptographer': "Develop and analyze algorithms to secure and protect information.",
    'Biomedical Scientist': "Conduct research to understand human diseases and develop treatments.",
    'Clinical Lab Technician': "Perform laboratory tests on patient samples to assist in diagnosis and treatment.",
    'Music Therapist': "Use music as a form of therapy to address physical, emotional, and cognitive needs.",
    'Technical Illustrator': "Create illustrations and diagrams to accompany technical documentation.",
    'Mortician': "Prepare bodies for burial or cremation and assist with funeral arrangements.",
    'Robotics Engineer': "Design and build robots for various applications.",
    'Speech Scientist': "Study speech production and perception.",
    'Tattoo Artist': "Create permanent designs on skin using needles and ink.",
    'Social Worker': "Provide support and assistance to individuals and families in need.",
    'Personal Shopper': "Assist individuals in selecting and purchasing clothing and accessories.",
    'Environmental Scientist': "Study the environment and solve environmental problems.",
    'FBI Agent': "Investigate federal crimes and enforce federal laws.",
    'Radiation Therapist': "Administer radiation treatments to cancer patients.",
    'Dental Hygienist': "Clean teeth, examine patients for oral diseases, and provide preventive dental care.",
    'Audiobook Narrator': "Record audio versions of books and other written material.",
    'Astronomer': "Study celestial bodies and phenomena in the universe.",
    'Nuclear Physicist': "Study the structure and behavior of atomic nuclei.",
    'Forensic Pathologist': "Perform autopsies and examine bodies to determine cause of death.",
    'Ethnobotanist': "Study the relationship between plants and people in different cultures.",
    'Cartographer': "Create maps and other geographic representations.",
    'Neuroscientist': "Study the brain and nervous system.",
    'Genetic Counselor': "Provide information and support to individuals and families about genetic disorders.",
    'Robotics Technician': "Install, maintain, and repair robots and robotic systems.",
    'Crime Scene Investigator': "Collect and analyze evidence from crime scenes.",
    'Astronaut': "Travel to space to conduct scientific research and explore new frontiers.",
    'Fine Artist': "Create original artwork using various mediums.",
    'Florist': "Design and arrange flowers for events and occasions.",
    'Wedding Planner': "Plan and coordinate weddings and related events.",
    'Film Director': "Direct the production of films and oversee creative decisions.",
    'Automotive Engineer': "Design and develop vehicles and automotive systems.",
    'Veterinary Surgeon': "Perform surgical procedures on animals.",
    'Wildlife Biologist': "Study animals and their habitats in natural environments.",
    'Music Producer': "Oversee the production and recording of music.",
    'Audio Engineer': "Operate and maintain audio equipment for recording and live performances.",
    'Biomedical Engineer': "Apply engineering principles to healthcare and medical technology.",
    'Food Scientist': "Study the physical, chemical, and microbiological properties of food.",
    'Forensic Toxicologist': "Analyze bodily fluids and tissues for toxins and drugs.",
    'Fashion Illustrator': "Create fashion sketches and illustrations.",
    'Bioinformatics Specialist': "Apply computational techniques to biological data analysis.",
    'Agricultural Scientist': "Study agricultural practices and develop new methods for crop production.",
    'Astrophysicist': "Study the physical properties and behavior of celestial bodies and phenomena.",
    'Furniture Designer': "Create designs for furniture pieces.",
    'Jeweler': "Design and create jewelry.",
    'Makeup Artist': "Apply makeup to enhance appearance for various purposes.",
    'Forensic Anthropologist': "Analyze skeletal remains to determine identity and cause of death.",
    'Tutor': "Provide academic instruction and support to students.",
    'Corporate Trainer': "Design and deliver training programs for employees.",
    'Biomedical Technician': "Install, maintain, and repair medical equipment and devices.",
    'Public Health Nurse': "Provide healthcare services and education to communities.",
    'Forensic Psychologist': "Apply psychology principles to criminal investigations and legal proceedings.",
    'Fashion Merchandiser': "Plan and coordinate the sale of fashion products.",
    'Cartoonist': "Create cartoons and comic strips.",
    'Medical Examiner': "Perform autopsies and determine cause of death in cases of suspicious or unexplained deaths.",
    'Urban Designer': "Plan and design urban spaces and environments.",
    'Botanist': "Study plant life and conduct research in botanical science.",
    'Ecologist': "Study the relationships between organisms and their environments.",
    'Marine Engineer': "Design, build, and maintain ships and other marine vessels.",
    'Industrial Designer': "Design products and systems to improve function, usability, and aesthetics.",
    'Digital Marketing Specialist': "Develop and implement digital marketing strategies.",
    'Bioinformatics Scientist': "Apply computational techniques to biological data analysis.",
    'Orthopedic Surgeon': "Diagnose and treat musculoskeletal injuries and conditions.",
    'Environmental Health Specialist': "Assess and mitigate environmental factors that affect human health.",
    'Physical Education Teacher': "Teach physical fitness, sports, and health-related topics.",
    'Green Architect': "Design environmentally sustainable buildings and structures.",
    'Conservationist': "Work to protect and preserve natural resources and ecosystems.",
    'Air Quality Analyst': "Monitor and analyze air quality to assess potential health and environmental risks.",
    'Oceanographer': "Study the oceans and marine life.",
    'Neurosurgeon': "Diagnose and surgically treat disorders of the nervous system.",
    'Wildlife Photographer': "Take photographs of wildlife in their natural habitats.",
    'Criminal Profiler': "Analyze crime scenes and criminal behavior to create profiles of suspects.",
    'Ecological Economist': "Study the relationship between the economy and the environment.",
    'Behavioral Analyst': "Study human behavior and provide interventions to address behavioral issues.",
    'Water Resource Engineer': "Design and manage water-related infrastructure and systems.",
    'Waste Management Specialist': "Develop and implement strategies for managing and disposing of waste.",
    'Urban Forester': "Manage and protect trees and green spaces in urban areas.",
    'Toxicologist': "Study the effects of chemicals and toxins on living organisms.",
    'Solar Energy Technician': "Install, maintain, and repair solar energy systems.",
    'Soil Conservationist': "Develop and implement strategies to prevent soil erosion and improve soil quality.",
    'River Guide': "Lead outdoor excursions and activities on rivers and waterways.",
    'Renewable Energy Consultant': "Advise clients on renewable energy technologies and systems.",
    'Recycling Coordinator': "Oversee recycling programs and initiatives.",
    'Aerospace Engineer': "Designing and developing aircraft, spacecraft, satellites, and missiles, ensuring they meet performance, safety, and efficiency standards.",
}

INTERESTS = {
    'Art': 101,
    'Technology': 102,
    'Science': 103,
    'Music': 104,
    'Sports': 105,
    'Writing': 106,
    'Cooking': 107,
    'Fashion': 108,
    'Health & Fitness': 109,
    'Photography': 110,
    'Travel': 111,
    'Nature & Environment': 112,
    'History': 113,
    'Film & Television': 114,
    'Gaming': 115,
    'Graphic Design': 116,
    'Coding': 117,
    'Psychology': 118,
    'Dance': 119,
    'Automobiles': 120,
    'Entrepreneurship': 121,
    'Animals & Pets': 122,
    'Reading': 123,
    'Social Media': 124,
    'Astronomy': 125,
    'Politics': 126,
    'Sculpture': 127,
    'Interior Design': 128,
    'Martial Arts': 129,
    'Baking': 130,
    'Graphic Novels & Comics': 131,
    'Architecture': 132,
    'Yoga & Meditation': 133,
    'Aviation': 134,
    'Cycling': 135,
    'DIY & Crafts': 136,
    'Theater': 137,
    'Urban Planning': 138,
    'Animation': 139,
    'Law & Justice': 140,
    'Foreign Languages': 141,
    'Fishing': 142,
    'Board Games': 143,
    'Education': 144,
    'Philosophy': 145,
    'Magic & Illusion': 146,
    'Camping & Hiking': 147,
    'Social Work': 148,
    'Surfing': 149,
    'DIY Electronics': 150
}

PROCESSING_PHRASES = [
    "Analyzing data streams",
    "Optimizing algorithm performance",
    "Rendering 3D models",
    "Encrypting data packets",
    "Calibrating sensor arrays",
    "Simulating quantum fluctuations",
    "Generating cryptographic keys",
    "Deploying neural network architectures",
    "Synchronizing distributed systems",
    "Compiling codebase dependencies",
    "Transmitting binary signals",
    "Refactoring legacy code",
    "Integrating API endpoints",
    "Rendering dynamic visualizations",
    "Testing edge cases",
    "Debugging recursive functions",
    "Initializing deep learning models",
    "Mining blockchain transactions",
    "Analyzing sentiment patterns",
    "Securing network protocols",
    "Verifying digital signatures",
    "Processing natural language queries",
    "Optimizing cloud infrastructure",
    "Modeling fluid dynamics",
    "Analyzing big data clusters",
    "Constructing Bayesian networks",
    "Implementing parallel processing",
    "Validating machine learning models",
    "Rendering photorealistic graphics",
    "Simulating quantum entanglement",
    "Training reinforcement learning agents",
    "Optimizing search algorithms",
    "Calibrating hardware sensors",
    "Deploying containerized applications",
    "Refining genetic algorithms",
    "Analyzing genetic sequences",
    "Optimizing compiler optimizations",
    "Encrypting end-to-end communications",
    "Defragmenting storage drives",
    "Generating synthetic datasets",
    "Analyzing neural network activations",
    "Compiling just-in-time bytecode",
    "Augmenting reality simulations",
    "Decrypting ciphertext messages",
    "Encoding multimedia streams",
    "Compiling optimized machine code",
    "Simulating chaos theory dynamics",
    "Refactoring database schemas",
    "Validating software architecture patterns",
    "Testing statistical hypotheses",
    "Mining cryptocurrency transactions",
    "Analyzing sentiment trends",
    "Securing network firewalls",
    "Verifying public key infrastructure",
    "Processing voice recognition queries",
    "Optimizing distributed ledger transactions",
    "Modeling weather patterns",
    "Analyzing high-dimensional data",
    "Constructing deep belief networks",
    "Implementing quantum algorithms",
    "Validating reinforcement learning policies",
    "Rendering virtual reality environments",
    "Simulating evolutionary dynamics",
    "Training generative adversarial networks",
    "Optimizing search engine indexing",
    "Calibrating satellite sensors",
    "Deploying serverless architectures",
    "Refining swarm intelligence algorithms",
    "Analyzing protein folding simulations",
    "Optimizing compiler heuristics",
    "Encrypting quantum communications",
    "Defragmenting solid state drives",
    "Generating adversarial examples",
    "Analyzing convolutional neural networks",
    "Compiling distributed computing tasks",
    "Augmenting mixed reality experiences",
    "Decrypting quantum cryptography",
    "Encoding genetic sequences",
    "Compiling optimized assembly code",
    "Simulating population dynamics",
    "Refactoring microservices architectures",
    "Validating blockchain consensus mechanisms",
    "Testing quantum entanglement phenomena",
    "Mining quantum cryptocurrency",
    "Analyzing quantum computing trends",
    "Securing quantum communication channels",
    "Verifying quantum key distribution",
    "Processing quantum error correction codes",
    "Optimizing quantum machine learning algorithms",
    "Modeling quantum annealing processes",
    "Analyzing quantum teleportation experiments",
    "Constructing quantum supremacy circuits",
    "Implementing quantum cryptography protocols",
    "Validating quantum algorithms",
    "Rendering quantum superposition states",
    "Simulating quantum decoherence phenomena",
    "Training quantum neural networks",
    "Optimizing quantum search algorithms",
    "Calibrating quantum sensors",
    "Counting unicorns in the cloud",
    "Determining the color of a chameleon in a bag of Skittles",
    "Translating Shakespeare into Klingon",
    "Convincing the coffee machine to brew a cup",
    "Finding the square root of negative pizza",
    "Debugging the toaster's attitude problem",
    "Deciphering the meaning of life, the universe, and everything",
    "Teaching a parrot to rap",
    "Measuring the aerodynamics of a rubber chicken",
    "Calculating the odds of winning a staring contest with a statue",
    "Balancing on one foot while juggling spaghetti",
    "Shuffling deck chairs on the Titanic",
    "Combing the desert for lost crumbs",
    "Solving the mystery of disappearing socks in the laundry",
    "Asking Alexa for relationship advice",
    "Performing a deep dive into shallow waters",
    "Playing hide and seek with a chameleon",
    "Cracking jokes with a calculator",
    "Searching for the lost city of Atlantis in the bathtub",
    "Analyzing the flight patterns of flying pigs",
    "Charging smartphones with positive vibes",
    "Dancing the robot with a Roomba",
    "Sorting M&M's by color preference",
    "Wrestling with spaghetti code",
    "Trying to lick your elbow",
    "Defeating the final boss in Minesweeper",
    "Plotting world domination on a napkin",
    "Finding Waldo in a crowd of penguins",
    "Searching for the remote control in a black hole",
    "Building sandcastles in virtual reality",
    "Writing a love letter to a chatbot",
    "Catching clouds with a butterfly net",
    "Solving a Rubik's cube blindfolded underwater",
    "Telling knock-knock jokes to a brick wall",
    "Explaining the concept of time to a goldfish",
    "Trying to catch a fart in a jar",
    "Singing lullabies to a computer",
    "Tuning a ukulele with a chainsaw",
    "Playing chess with a pigeon",
    "Walking a pet rock",
    "Convincing a mirror to reflect on its life choices",
    "Dancing the cha-cha-cha with a penguin",
    "Putting lipstick on a pig",
    "Trying to outsmart a banana peel",
    "Counting the grains of sand on a beach",
    "Teaching a dog to recite Shakespeare",
    "Solving a crossword puzzle in reverse",
    "Finding a needle in a haystack while blindfolded",
    "Playing hide and seek with your shadow",
    "Attempting to high-five a ghost",
    "Having a staring contest with a goldfish",
    "Playing chess against a pigeon",
    "Wrestling with a jellyfish",
    "Trying to convince a cat to take a bath",
    "Finding the end of a rainbow",
    "Catching fog in a net",
    "Teaching a snail to breakdance",
    "Solving a crossword puzzle with a pen without making any mistakes",
    "Juggling flaming torches in a wind tunnel",
    "Putting socks on a rooster",
    "Teaching a fish to ride a bicycle",
    "Herding cats",
    "Playing hopscotch with a kangaroo",
    "Trying to tickle yourself",
    "Playing chess with a computer and losing",
    "Dancing in the rain with an umbrella",
    "Trying to read a book with your eyes closed",
    "Playing hide and seek with the wind",
    "Walking on stilts in a hurricane",
    "Trying to balance a spoon on your nose",
    "Catching a snowflake with your tongue",
    "Teaching a penguin to fly",
    "Trying to solve a Rubik's cube in the dark",
    "Having a thumb war with a robot",
    "Playing leapfrog with a unicorn",
    "Singing a duet with a parrot",
    "Trying to fit a square peg into a round hole",
    "Playing tag with a cheetah",
    "Trying to count all the stars in the sky",
    "Solving a mystery with a magnifying glass and a rubber chicken",
    "Trying to teach an old dog new tricks",
    "Playing chess against yourself and losing",
    "Trying to put toothpaste back into the tube",
    "Having a staring contest with a statue",
    "Trying to lick your elbow",
    "Playing catch with a boomerang"
]

def eliminate_options(responses: list, options: dict) -> tuple[list, list]:
    eliminated_options = []
    passed_options = []
    for i in range(len(responses)):
        for j in range(len(options)):
            if responses[i] in list(options.values())[j] and list(options.keys())[j] not in eliminated_options:
                removed = list(options.keys())[j]
                eliminated_options.append(removed)
    for key in options.keys():
        if key not in eliminated_options:
            passed_options.append(key)
    return passed_options, eliminated_options

def sort_by_interest(met_criteria:list, not_met:list, careers:dict, interests:list) -> tuple:
    interest_count = {}
    if len(met_criteria) > 2:
       for i in met_criteria:
           interest_count.update({i:0})
    else:
        for i in met_criteria:
            interest_count.update({i:1})
        for i in range(3-len(met_criteria)):
            interest_count.update({not_met.pop():0})
    for i in range(len(list(interest_count.keys()))):
        for j in range(len(interests)):
            if interests[j] in careers[list(interest_count.keys())[i]]:
                interest_count[list(interest_count.keys())[i]] += 1
    sorted_interests = sorted(interest_count.items(), key=lambda x: x[1])
    return ((sorted_interests)[-1][0], (sorted_interests)[-2][0], (sorted_interests)[-3][0])

def get_career_recommendations(responses: list, interests: list, careers: dict) -> tuple:
    return sort_by_interest(eliminate_options(responses, careers)[0], eliminate_options(responses, careers)[1], careers, interests)

def convert_to_stream(string: str):
    for word in string.split(' '):
        sleep(0.05)
        yield word + ' '

st.title('Career Recommendation System')
st.write("Welcome to our career recommendation tool! 🌟 Please keep in mind that our algorithm is a work in progress, crafted over just four days with limited data for training. While we've done our best to provide personalized suggestions based on your survey responses, it's important to acknowledge that our results may not be as accurate as we aspire them to be. We're continuously refining our system to improve accuracy and relevance. Thank you for your understanding and patience as we evolve!")
st.divider()
st.subheader('Please answer the following questions to get started.')
q1 = st.toggle('I am willing to attend a 2-year or 4-year university.')
q2 = st.toggle('I am willing to work a job with high levels of physical activity.')
q3 = st.toggle('I am willing to work in an outdoor environment.')
q4 = st.toggle('I am willing to work personally with clients.')
q5 = st.toggle('I am willing to work with children.')
responses = [q1, q2, q3, q4, q5]
interests = st.multiselect('Select all that interest you:', list(INTERESTS.keys()))
interests = [INTERESTS[i] for i in interests]
response_numbers = []
for i in range(len(responses)):
    if not responses[i]:
        response_numbers.append(i + 1)
if q1 or q2 or q3 or q4 or q5:
    st.write("Thank you for your responses! Now, let's see what we can do for you.")
    with st.spinner(choice(PROCESSING_PHRASES)):
        sleep(3)
    recommendations = get_career_recommendations(response_numbers, interests, CAREER_OPTIONS)
    columns = st.columns(3)
    with columns[0]:
        st.subheader(recommendations[0])
        st.write_stream(convert_to_stream(CAREER_DESCRIPTIONS[recommendations[0]]))
    with columns[1]:
        st.subheader(recommendations[1])
        st.write_stream(convert_to_stream(CAREER_DESCRIPTIONS[recommendations[1]]))
    with columns[2]:
        st.subheader(recommendations[2])
        st.write_stream(convert_to_stream(CAREER_DESCRIPTIONS[recommendations[2]]))
else:
    st.write('Please answer at least one question to get started.')